Feat/readme file templates
eoscostarica/guide.eoscostarica.io pull request #204
Opened 2021-01-08 14:16 UTC by leisterfrancisco

### GH Issue

Resolves #202  

### Steps to test
1. Open developer guidelines tag
1. Check README template tag exist
1. Check content is right

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-01-11 20:01 UTC, xavier506 commented on docs/readme-file-template.md
> +## Teach Stack
@leisterfrancisco   'Tech Stack'

2021-01-11 20:02 UTC, xavier506 commented on docs/readme-file-template.md
> +
Let's add the logo

2021-01-11 20:02 UTC, xavier506 commented on docs/readme-file-template.md
> +## About Company
About EOS Costa Rica

2021-01-11 20:02 UTC, xavier506 requested changes
Please see my comments

2021-01-12 19:55 UTC, xavier506 approved these changes
LGTM

2021-01-12 19:56 UTC, steph222 approved these changes

2021-01-12 19:56 UTC, merged

2021-01-12 19:56 UTC, edgarEOS approved these changes
👍