feat(doc): Add a new GitHub Keys guide section under tutorials
eoscostarica/guide.eoscostarica.io pull request #227
Opened 2021-01-14 22:25 UTC by edgarEOS

### GH Issue

Resolves #218 

### Steps to test
1. Open Tutorials 
1. Go to GitHub Keys
1. Check Content

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-01-14 23:19 UTC, leisterfrancisco requested changes

2021-01-14 23:19 UTC, leisterfrancisco commented on docs/tutorials/github-keys.md
> +Let's first defined GitHub as a browser-based online control system of distributed version for those software developers using the Git revision control system. Git uses SSH public key authentication
**Authetication** word has grammatical spelling error

2021-01-14 23:19 UTC, leisterfrancisco commented on docs/tutorials/github-keys.md
> +This guide is for Windows users , more information for Linux and Mac [on this site](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding
In this phrase, "This guide is for Windows users ," there is an extra empty space, before the comma mark.

2021-01-14 23:19 UTC, leisterfrancisco commented on docs/tutorials/github-keys.md
> +Windows environments do not have a standard default unix shell. External shell programs will need to be installed for to have a complete keygen experience. The most straight forward option is to util
I think could be better that unix word go with capital letter, so then, the result will be **U**nix

2021-01-14 23:19 UTC, leisterfrancisco commented on docs/tutorials/github-keys.md
> +- At the prompt , type a secure passphrase. For security reasons it should be as complex as possible.
In this phrase, "At the prompt ," there is an extra empty space, before the comma mark.

2021-01-14 23:19 UTC, leisterfrancisco commented on docs/tutorials/github-keys.md
> +- It will ask for a file to save the key , just press enter. This accepts the default file location.
In this phrase, "It will ask for a file to save the key ," there is an extra empty space, before the comma mark.

2021-01-18 17:11 UTC, xavier506 commented on docs/tutorials/github-keys.md
> +Let's first defined GitHub as a browser-based online control system of distributed version for those software developers using the Git revision control system. Git uses SSH public key authentication
let's first define...

2021-01-18 17:39 UTC, xavier506 submitted a review, later dismissed
LGTM

2021-01-18 17:42 UTC, xavier506 commented
@edgarEOS  let me know if you need any help resolving the conflict so we can get this PR merged

2021-01-18 17:45 UTC, leisterfrancisco requested changes

2021-01-18 17:45 UTC, leisterfrancisco commented on docs/tutorials/github-keys.md
> +Let's first define GitHub as a browser-based online control system of distributed version for those software developers using the Git revision control system. Git uses SSH public key authetication an
Sorry if I don't explained clearly last time, the word is not authetication is authentication, and the paragraph, this word appear two times.

>Git uses SSH public key **authetication** and not a password **authetication**

2021-01-18 20:00 UTC, leisterfrancisco requested changes

2021-01-19 19:39 UTC, leisterfrancisco approved these changes

2021-01-19 19:40 UTC, steph222 approved these changes

2021-01-19 19:40 UTC, merged