update(devops): Add new content
eoscostarica/guide.eoscostarica.io pull request #248
Opened 2021-01-21 21:23 UTC by Edgar097

### GH Issue

Resolves #237  

### Steps to test
1.  Open DevOps
1. Check Content

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-01-21 21:26 UTC, Edgar097 commented
There are several images that I need to complete this section , however it will be nice if @ldrojas and @xavier506 can check the content and the distribution of the infromation. Thank you

2021-01-21 22:57 UTC, xavier506 submitted a review, later dismissed
LGTM

2021-01-22 15:31 UTC, steph222 approved these changes

2021-01-22 15:31 UTC, steph222 approved these changes

2021-01-22 16:29 UTC, leisterfrancisco requested changes

2021-01-22 16:29 UTC, leisterfrancisco commented on docs/devops.md
> +![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/c7bc6509-de0a-4efd-aa9c-f3a4486809b5/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/c7bc6509-de0a-4efd-aa9c-f3
I can't see this content

2021-01-22 16:29 UTC, leisterfrancisco commented on docs/devops.md
> +![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/70d28084-e01c-4807-9dce-d106519ba31c/CI_Example.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/70d28084-e01c-4807-9dce-
I can't see this content

2021-01-22 16:29 UTC, leisterfrancisco commented on docs/devops.md
> +![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/db2bfb4e-779e-4c7b-9933-05cb788f5008/CD_Example.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/db2bfb4e-779e-4c7b-9933-
I can't see this content

2021-01-22 21:26 UTC, leisterfrancisco submitted a review, later dismissed
Good work 👍

2021-01-23 01:48 UTC, xavier506 commented on docs/devops.md
> +- Continuous Integration (CI): Addresses building software from contributions of individual developers in a controlled, agile way. (Checking all code into centralized repo daily)
lets bold list item titles 

- **Continuous Integration (CI)**: Addresses bui

2021-01-23 01:48 UTC, xavier506 commented on docs/devops.md
> +```shell
👍

2021-01-23 01:49 UTC, xavier506 requested changes
please see minor formatting changes

2021-01-25 16:52 UTC, xavier506 approved these changes
LGTM

2021-01-25 16:54 UTC, xavier506 submitted a review, later dismissed

2021-01-26 15:29 UTC, xavier506 approved these changes
LGTM

2021-01-26 15:34 UTC, steph222 approved these changes

2021-01-26 18:37 UTC, xavier506 commented on docs/devops.md
> +## Why do DevOps?
Why implement DevOps?

2021-01-26 20:22 UTC, xavier506 commented on docs/devops.md
> +**-Phoenix Project**
Let's add `**-Phoenix Project**` inside the quote block like this : 

***
>“*The competitive advantage this capability creates is enormous, enabling faster feature time to market, increased customer satisfaction, market share, employee productivity, and happiness.”*
**-Phoenix Project**
***

2021-01-27 16:42 UTC, xavier506 approved these changes
LGTM

2021-01-27 17:06 UTC, leisterfrancisco approved these changes
Good work 👍

2021-01-27 17:28 UTC, steph222 approved these changes
Good work!!

2021-01-27 17:57 UTC, merged