update(developer-tools): add new content
eoscostarica/guide.eoscostarica.io pull request #285
Opened 2021-02-01 18:10 UTC by Edgar097

### GH Issue

Resolves #262  

### Steps to test
1. Open Our Favorite Tooles 
1. Check Content

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-02-01 20:07 UTC, steph222 commented
@Edgar097  add this information 😄 

## Apollo

###  What is  Apollo?

Apollo is a suite of tools to create a GraphQL server, and to consume a GraphQL API.  Apollo is a team and community that builds on top of GraphQL, and provides different tools that help you build your projects.

### Why we use  Apollo?

1. **Documentation:** While Apollo continues to evolve, the team and community behind it keeps the documentation up to date, and they have plenty of insight about how to build applications. 
2. **Libraries:** Apollo offers plenty of libraries for implementing an effective GraphQL tech stack for JavaScript applications, and their libraries are open-sourced to be more manageable.
3.  **Features:** Apollo comes with built-in features to pull all the complexity out of applications and handle the intersection between client and server applications.

### Instalation of Apollo

[Apollo CLI Instalation](https://www.apollographql.com/docs/devtools/cli/)

[Apollo GitHub](https://github.com/apollographql)

* * *

## Axios

###  What is Axios?

Axios is a very popular JavaScript library you can use to perform HTTP requests, that works in both Browser and Node.js platforms. It supports all modern browsers, including support for IE8 and higher.

### Why we use Axios?

1. Supports older browsers.
2. Has a way to abort a request.
3. Has a way to set a response timeout.
4. has built-in CSRF protection.
5. Supports upload progress.
6. Performs automatic JSON data transformation.
7. Works in Node.js

### Instalation of Axios

[Axios Instalation](https://www.npmjs.com/package/axios)

[Axios GitHub](https://github.com/axios/axios)

2021-02-01 20:49 UTC, leisterfrancisco requested changes

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +2. **Reusable Components**. React provides a component based structure. Components are your lego pieces. You start with tiny components like button, checkbox, dropdown etc. and the you create wrapper
> checkbox, dropdown etc. and the you create

Not sure about that point

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +5. **Support**, for custom HTTP header and supports arbitrary request data..
> request data..

Double end point

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +7. **Plugins** to support additional feature.
We could use `:` or `,` but use the same one for the whole context

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +### PostMan Installation
PostMan -> Postman

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +[PostMan Installation](https://www.softwaretestingmaterial.com/install-postman/)
PostMan -> Postman

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +[PostMan GitHub](https://github.com/postmanlabs)
PostMan -> Postman

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +### httpie Installation
httpie -> HTTPie

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
>  ## httpie
httpie -> HTTPie

2021-02-01 20:49 UTC, leisterfrancisco commented on docs/developer-tools.md
> +[Hsura GitHub](https://github.com/hasura)
Hsura GitHub - > Hasura GitHub

2021-02-01 21:08 UTC, Edgar097 commented
> @Edgar097 add this information 😄
> 
> ## Apollo
> ### What is Apollo?
> Apollo is a suite of tools to create a GraphQL server, and to consume a GraphQL API. Apollo is a team and community that builds on top of GraphQL, and provides different tools that help you build your projects.
> 
> ### Why we use Apollo?
> 1. **Documentation:** While Apollo continues to evolve, the team and community behind it keeps the documentation up to date, and they have plenty of insight about how to build applications.
> 2. **Libraries:** Apollo offers plenty of libraries for implementing an effective GraphQL tech stack for JavaScript applications, and their libraries are open-sourced to be more manageable.
> 3. **Features:** Apollo comes with built-in features to pull all the complexity out of applications and handle the intersection between client and server applications.
> 
> ### Instalation of Apollo
> [Apollo CLI Instalation](https://www.apollographql.com/docs/devtools/cli/)
> 
> [Apollo GitHub](https://github.com/apollographql)
> 
> ## Axios
> ### What is Axios?
> Axios is a very popular JavaScript library you can use to perform HTTP requests, that works in both Browser and Node.js platforms. It supports all modern browsers, including support for IE8 and higher.
> 
> ### Why we use Axios?
> 1. Supports older browsers.
> 2. Has a way to abort a request.
> 3. Has a way to set a response timeout.
> 4. has built-in CSRF protection.
> 5. Supports upload progress.
> 6. Performs automatic JSON data transformation.
> 7. Works in Node.js
> 
> ### Instalation of Axios
> [Axios Instalation](https://www.npmjs.com/package/axios)
> 
> [Axios GitHub](https://github.com/axios/axios)

Thanks!

2021-02-02 04:30 UTC, xavier506 submitted a review, later dismissed
LGTM

2021-02-02 13:20 UTC, leisterfrancisco requested changes

2021-02-02 13:20 UTC, leisterfrancisco commented on docs/developer-tools.md
> +Apollo is a suite of tools to create a GraphQL server, and to consume a GraphQL API.  Apollo is a team and community that builds on top of GraphQL, and provides different tools that help you build yo
> GraphQL server, and to consume

Not sure about this comma

2021-02-02 13:20 UTC, leisterfrancisco commented on docs/developer-tools.md
> +Javascript is not a strongly typed language, this might create some problems for the developers. PropTypes is a library that helps when you need to resolve a problem related with this. Checking the t
specificaction -> specification

2021-02-02 13:20 UTC, leisterfrancisco commented on docs/developer-tools.md
> +2. **Automation:**  Automated tests can be easily set up using the Postman API testing tool. You can automate your test cases in Postman in javascript with impressive features like write test suites,
javascript  -> JavaScript

2021-02-02 20:37 UTC, leisterfrancisco approved these changes
Good work 👍

2021-02-02 22:25 UTC, steph222 approved these changes
Good Job 💯

2021-02-02 22:25 UTC, merged