update(tools): add new section for ui/ux
eoscostarica/guide.eoscostarica.io pull request #315
Opened 2021-02-08 20:35 UTC by Edgar097

### GH Issue

Resolves #305 

### Steps to test
1. Check Ux-UI Tools
1. Useful Links

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-02-08 20:48 UTC, steph222 submitted a review, later dismissed
LGTM!!

2021-02-09 14:32 UTC, leisterfrancisco requested changes

2021-02-09 14:32 UTC, leisterfrancisco commented on docs/ux_and_ui.md
> +### Sketch Installation?
Why question mark?

2021-02-09 14:32 UTC, leisterfrancisco commented on docs/ux_and_ui.md
> +### What is Material.io
Missing question mark, or well, in others titles, remove that one to make it consistent

2021-02-09 14:33 UTC, leisterfrancisco commented
Solve docs/community-resources/useful-links.md conflict

2021-02-10 17:38 UTC, leisterfrancisco approved these changes
Good work 👍

2021-02-10 17:38 UTC, steph222 submitted a review, later dismissed

2021-02-11 14:51 UTC, xavier506 commented on docs/community-resources/useful-links.md
> +**UX/UI**
Should we use a header tag?

2021-02-11 15:07 UTC, murillojorge commented
Reviewing

2021-02-11 15:11 UTC, murillojorge commented on docs/ux_and_ui.md
> +Zeplin facilitates the transfer of designs by taking them from Sketch, Adobe XD, Figma, and Photoshop and exporting them into a format that can easily generate code snippets, style guides, specs, and
It's also used as a source of truth for design deliveries.

2021-02-11 15:13 UTC, murillojorge commented on docs/ux_and_ui.md
> +It is a graphic editor for macOS developed by Dutch Company.
It is a web design vector-based graphic editor...

2021-02-12 16:59 UTC, xavier506 approved these changes
LGTM 

@Edgar097  did the changes jorge requested get put into the spanish version also?

2021-02-12 18:38 UTC, steph222 submitted a review, later dismissed

2021-02-13 03:13 UTC, merged