Docs/private network installation tutorial
eoscostarica/guide.eoscostarica.io pull request #317
Opened 2021-02-08 21:57 UTC by JustinCast

### GH Issue

#268

### Steps to test
1. `yarn start`
1. Go to `localhost:3000` and search private-network-tutorial resource

#### CheckList
- [x] Follow proper Markdown format
- [x] The content is adequate
- [x] The content is available in both english and spanish
- [x] I Ran a spell check

2021-02-09 14:44 UTC, leisterfrancisco requested changes

2021-02-09 14:44 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation-tutorial.md
>  # Private network installation tutorial
Capital case

2021-02-09 14:44 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation-tutorial.md
>  # API node: configuration and execution
Capital case

2021-02-09 14:44 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation-tutorial.md
> +# Stop the nodeos service
Capital case

2021-02-09 14:44 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation-tutorial.md
> +# Reboot the nodeos service
Capital case

2021-02-09 14:44 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation-tutorial.md
> +# Reboot nodeos from scratch
Capital case

2021-02-09 14:44 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation-tutorial.md
> +# Interacting with the network
Capital case

2021-02-09 14:44 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation-tutorial.md
> +## Get stored data
Capital case

2021-02-09 14:45 UTC, leisterfrancisco requested changes

2021-02-09 14:45 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation.md
>  # Software requirements
Title Case

2021-02-09 14:45 UTC, leisterfrancisco commented on docs/tutorials/private-network-installation.md
>  # Private network installation tutorial
Title Case

2021-02-10 16:29 UTC, leisterfrancisco submitted a review, later dismissed
Good work 👍

2021-02-10 17:09 UTC, Edgar097 submitted a review, later dismissed

2021-02-11 14:50 UTC, xavier506 commented on docs/tutorials/private-network-installation.md
> +# Private Network Installation Tutorial
Lets start with H2 tags since the H1 is always the page title

2021-02-13 03:15 UTC, xavier506 approved these changes
LGTM

2021-02-13 03:15 UTC, merged