Feat/add ricardian content
eoscostarica/guide.eoscostarica.io pull request #354
Opened 2021-07-02 16:29 UTC by leisterfrancisco

### What does this PR do ?
Add clauses and contracts explanation of a Ricardian Contract

### Steps to test
1. yarn install
1. yarn start
1. go to http://localhost:3000/docs/eos-learn/ricardian-contracts/

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-07-02 19:38 UTC, AngeloCG97 reviewed
Review conflicts

2021-07-04 22:04 UTC, xavier506 commented on docs/eos-learn/ricardian-contracts.md
>  Blockchains operate under smart contracts, however, work is underway to include Ricardian contracts in the transactions of these networks. One of the main objectives is to convert the complexity of t
lets include a link to view an example Ricardian contract on our components storybook:

https://components.eosio.cr/?path=/story/ricardiancontract--ricardian-contract

2021-07-04 22:12 UTC, xavier506 requested changes
Eos costa rica has developed a react component that renders ricardian contracts for smart contracts on EOSIO networks. You can view the react component in the foollowing link.

https://components.eosio.cr/?path=/story/ricardiancontract--ricardian-contract

the open source repository for  this component is located here:  https://github.com/eoscostarica/eoscr-components

2021-07-07 18:49 UTC, xavier506 commented on docs/eos-learn/ricardian-contracts.md
> +EOS COSTA RICA has developed a react component that renders ricardian contracts for smart contracts on EOSIO networks. You can view the react component in the following [link](https://components.eosi
EOS Costa Rica

2021-07-07 20:37 UTC, xavier506 approved these changes
LGTM

2021-07-07 20:38 UTC, merged