(docs): add blockchain security video
eoscostarica/guide.eoscostarica.io pull request #373
Opened 2022-01-04 21:26 UTC by hanakoori01

### What does this PR do ?

- Resolves #280 
- Resolves #360 

### Steps to test
1. Run `yarn start` 
2. Go to `localhost:3000`
3. Go to Developer Guidelines>Learn EOSIO> Security 
4. Go to Developer Guidelines> Tutorials > Markdown Guide

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-01-04 21:47 UTC, xavier506 commented on docs/eos-learn/blockchain-security.md
> +## Blowing up vulnerabilities in Blockchain
Blowing up is not the right term , seems its from a translation error (explotando = exploding = blowing up)

2022-01-04 21:48 UTC, xavier506 commented on docs/tutorials/markdown-guide.md
> +But let's throw in a <b>tag</b>.
is this going to work outside of a ``` code block ``` ?

2022-01-04 21:59 UTC, hanakoori01 commented on docs/eos-learn/blockchain-security.md
> +## Blowing up vulnerabilities in Blockchain
Okay, I'm going to change it

2022-01-05 19:08 UTC, xavier506 requested changes
great work!

please see my comments

2022-01-05 19:08 UTC, xavier506 commented on docs/eos-learn/blockchain-security.md
> +## Exploding vulnerabilities in Blockchain
@hanakoori01 I think the word you are looking for is "exploiting"

2022-01-05 19:08 UTC, xavier506 commented on docs/tutorials/markdown-guide.md
> +**Ejemplo:**
spanish

2022-01-05 19:08 UTC, xavier506 commented on docs/tutorials/markdown-guide.md
> +#### *Javascript*
i believe code syntax highlighting is specific to
docusaurus, its ok to mention it here  just make a note that some markdown is github specific and another is docusaurus specific

2022-01-06 15:05 UTC, xavier506 commented on docs/eos-learn/blockchain-security.md
> +## Exploding vulnerabilities in Blockchain
@hanakoori01 it would also be great to get an intro text for this video 

Maybe @kuronosec can help us come up with a short text

2022-01-06 15:09 UTC, xavier506 commented on docs/eos-learn/blockchain-security.md
> +## Blowing up vulnerabilities in Blockchain
try this word: exploiting

2022-01-06 17:30 UTC, xavier506 approved these changes
LGTM

2022-01-06 17:30 UTC, merged