docs(common): Added Run Boilerplate #41
eoscostarica/guide.eoscostarica.io pull request #490
Opened 2022-07-07 21:34 UTC by fvives99

### Title

### What does this PR do?

- resolves https://github.com/eoscostarica/full-stack-boilerplate/issues/41

### Steps to test
1. Navigate to the tutorials section
2. See Run the boilerplate section on the sidebar

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-07-11 17:22 UTC, JAMares requested changes

2022-07-11 17:22 UTC, JAMares commented on docs/tutorials/run-boilerplate.md
> +- [docker-compose](https://docs.docker.com/compose/)
see my comments in Spanish

2022-07-21 01:25 UTC, xavier506 requested changes
# Lets re arrange this list a bit :

## EOS Boilerplates 

- [Full Stack Boilerplate](https://github.com/eoscostarica/full-stack-boilerplate)
- [Front End](https://github.com/eoscostarica/backend-boilerplate)
- [Back End](https://github.com/eoscostarica/backend-boilerplate)

## WAX Boilerplates 

- [WAX WebApp](https://github.com/edenia/wax-webapp-boilerplate)
- [Wax Full Stack Boilerplate](https://github.com/edenia/wax-full-stack-boilerplate)

## PROTON Boilerplate 

- [Proton Full Stack Boilerplate](https://github.com/edenia/proton-full-stack-boilerplate)

## General Boilerplates 

- [WebApp Boilerplate](https://github.com/eoscostarica/webapp-boilerplate)
- [Hapi Boilerplate](https://github.com/eoscostarica/hapi-boilerplate)
- [Hasura Boilerplate](https://github.com/eoscostarica/hasura-boilerplate)

2022-07-21 01:25 UTC, xavier506 commented on docs/boilerplate.md
> +## PROTON Boilerplate
No need for all CAPS here

2022-07-22 00:15 UTC, xavier506 approved these changes
LGTM

2022-07-22 16:04 UTC, warnerHurtado approved these changes
LGTM

2022-07-22 16:06 UTC, xavier506 approved these changes
LGTM

2022-07-22 16:06 UTC, merged