feat(frontend): Improved footer styles #471
eoscostarica/guide.eoscostarica.io pull request #541
Opened 2022-07-27 06:11 UTC by fvives99

### Improve footer styles

### What does this PR do?

- resolves #471 
Note: react-icons was installed: npm install react-icons --save or yarn install react-icons

### Steps to test
1. Navigate to the bottom of [guide.eosio](https://guide.eoscostarica.io/) and see page footer

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-07-27 06:12 UTC, fvives99 commented
![image](https://user-images.githubusercontent.com/55892352/181174347-7db9bbc1-0d39-446d-a8f8-5a898d81767d.png)

2022-07-27 06:13 UTC, fvives99 commented
![image](https://user-images.githubusercontent.com/55892352/181174386-60fbe47d-091e-4c78-a5ad-75f91c96b174.png)

2022-07-27 17:49 UTC, AngeloCG97 commented on src/theme/Footer/index.js
> + //import Link from '@docusaurus/Link';
Please remove this comment

2022-07-27 17:49 UTC, AngeloCG97 commented on src/theme/Footer/index.js
> +
Please reduce spaces

2022-07-27 17:52 UTC, AngeloCG97 commented on src/theme/Footer/index.js
> +               <Box border={1} borderTop={0} borderBottom={0} borderColor={'#BDBDBD'} paddingLeft={20}>
Unecessary curly brases in borderColor={'#BDBDBD'}

2022-07-27 17:57 UTC, AngeloCG97 commented
> ![image](https://user-images.githubusercontent.com/55892352/181174347-7db9bbc1-0d39-446d-a8f8-5a898d81767d.png)

Please paste screen mobile version

2022-07-27 17:58 UTC, AngeloCG97 commented
Please resolve conflict

2022-07-29 16:56 UTC, AngeloCG97 commented on src/theme/Footer/index.js
> +     console.log(isDarkTheme)
Please move this comment

2022-07-29 17:09 UTC, fvives99 commented on src/theme/Footer/index.js
> +     console.log(isDarkTheme)
What comment?

2022-07-29 17:31 UTC, fvives99 commented on src/theme/Footer/index.js
> +     console.log(isDarkTheme)
removed

2022-08-02 05:04 UTC, xavier506 approved these changes
LGTM

2022-08-02 14:10 UTC, AngeloCG97 approved these changes
LGTM

2022-08-02 16:30 UTC, xavier506 requested changes
@fvives99 

Are you able to run `yarn build` on this branch?

2022-08-03 15:02 UTC, fvives99 commented
> @fvives99
> 
> Are you able to run `yarn build` on this branch?

Will fix asap

2022-08-03 23:56 UTC, fvives99 commented
> > ![image](https://user-images.githubusercontent.com/55892352/181174347-7db9bbc1-0d39-446d-a8f8-5a898d81767d.png)
> 
> Please paste screen mobile version

![image](https://user-images.githubusercontent.com/55892352/182733482-7d118bc4-66ec-4623-bae5-7cebfb555830.png)

2022-08-07 03:46 UTC, xavier506 approved these changes
LGTM

2022-08-07 03:46 UTC, merged